# ─── Product Service Deployment ─── WorkerNode1 ─────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product-ns
  labels:
    app: product-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-service
        tier: backend
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: hpe/node-group
                    operator: In
                    values:
                      - worker1

      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service.ecommerce.svc.cluster.local:27017"
            - name: DB_NAME
              value: "productdb"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
