FROM python:3.11-slim

WORKDIR /app

COPY event-processor-requirements.txt .

RUN pip install --no-cache-dir -r event-processor-requirements.txt

COPY event-processor.py .

CMD ["python", "event-processor.py"]